### ISSUE TITLE
Error on "create" from 3.1.0

### ISSUE THREAD

**Issue by palasjir** [clebert/aws-simple#98]
Encountered following error when working with aws-simple :

```
aws-simple--dealer-search--eeee7170: creating CloudFormation changeset...
 ❌  aws-simple--dealer-search--eeee7170 failed: Error [ValidationError]: Template may not exceed 460800 bytes in size.
    at Request.extractError (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2020-05-27T09:17:59.184Z,
  requestId: 'd2b2659f-d319-4aff-9d19-2db5ea8f3687',
  statusCode: 400,
  retryable: false,
  retryDelay: 173.8271312125218
}
Template may not exceed 460800 bytes in size.
```
This happen when we tried to update to latest version of aws-simple@3.1.0 and aws-cdk@1.41.0 . When using aws-cdk lower than 1.41 the error was:
```
Cloud assembly schema version mismatch: Maximum schema version supported is 3.0.0, but found 4.0.0.
```

**Comment by clebert** [comment]
**To the first error:** This seems to be a general limit for CF templates. The template is generated by the CDK based on your config. See Limits: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html

It is recommended to work with nested stacks. I do not know if this can be mapped with `aws-simple` in a meaningful way. Either reduce the complexity of your stack or split it up into multiple configs. Strange that this only happens with CDK 1.41.0.

**To the second error:** According to this page: https://docs.aws.amazon.com/cdk/latest/guide/reference.html
You have probably included the wrong version of the `construct` library. Try to select the CDK compatible version.

**Comment by palasjir** [comment]
We discovered where the problem was. The cause was the changed build process that generated more build files into `dist` folder. So with following config:
```
...
s3Configs: [
      {
        type: 'folder',
        publicPath: '/assets/feature-app',
        localPath: path.join(__dirname, 'packages/feature-app/dist'),
        responseHeaders: {cacheControl},
        cachingEnabled: false,
      },
     ...
]
...
```
it was failing. Pruning the files helped.

Strange is that with old version of `aws-simple` this was working fine. Which brings me to if there isn't some other problem.

This might my lack of the knowledge but how is the number of files to be uploaded connected with the size of cloud formation template? I thought that the template should just define which buckets are created and not theirs content.

**Comment by clebert** [comment]
We have recently changed the mechanics regarding the integration of S3 files. This change was introduced with patch version 2.0.1. API technically it was a non breaking change. What you have experienced now is of course unpleasant. In order to support binary file types correctly, we are currently creating a separate S3 integration for each file in the API gateway. That means the template size correlates with the number of files. This is a circumstance that we did not consider back then. Maybe we have to find another solution.

FYI: @unstubbable

**Comment by unstubbable** [comment]
I agree, we should reconsider this.

**Comment by palasjir** [comment]
That would be awesome if you could reconsider this. We now added additional feature app into the config and getting the following error:

```
aws-simple--dealer-search--df3e4b06: creating CloudFormation changeset...

 ❌  aws-simple--dealer-search--df3e4b06 failed: Error [ValidationError]: Template format error: Number of resources, 203, is greater than maximum allowed, 200
    at Request.extractError (/home/runner/work/dealer-search/dealer-search/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/runner/work/dealer-search/dealer-search/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/runner/work/dealer-search/dealer-search/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/runner/work/dealer-search/dealer-search/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/runner/work/dealer-search/dealer-search/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/runner/work/dealer-search/dealer-search/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/runner/work/dealer-search/dealer-search/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/runner/work/dealer-search/dealer-search/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/runner/work/dealer-search/dealer-search/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/runner/work/dealer-search/dealer-search/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2020-06-05T14:36:19.747Z,
  requestId: 'd590bff5-045b-473b-a876-9851e0dceef8',
  statusCode: 400,
  retryable: false,
  retryDelay: 235.9828873873362
}
```

It looks like there are always 3 resources created per file included in the folder.
